//--------------------URL CONSTANTS-------------------------------------

export const URLS = {
  loginExpired: "/loginExpired",
  pageNotFound: "/page-not-found",
  userDashboard: "/userDashboard",  
  LoginPage: "/",  
  testReport:"/testReport",
  redirectLoginPage: "/login",  
  companyMaster: "/companyMaster",  
  addNewCompany:"/addNewCompany",
  editCompany:"/editCompany",
  report1:"/report1",
  countryMaster:"/countryMaster",
  addCountry:"/addCountry",
  editCountry:"/editCountry",
  stateMaster:"/stateMaster",
  addState:"/addState",
  editState:"/editState",
  addDestination:"/addDestination",
  editDestination:"/editDestination",
  userMaster:"/userMaster",
  addUser:"/addUser",
  editUser:"/editUser",
  branchMaster:"/branchMaster",
  editBranch:"/editBranch",
  addBranch:"/addBranch",
};
