//--------------------URL CONSTANTS-------------------------------------

export const URLS = {
  Ftptest:"/Ftptest",
  testformat:"/testformat",
  pageNotFound:"/pageNotFound",
  loginExpired: "/loginExpired",  
  userDashboard: "/userDashboard",  
  LoginPage: "/",  
  testReport:"/testReport",
  redirectLoginPage: "/login",  
  companyMaster: "/companyMaster",  
  addNewCompany:"/addNewCompany",
  editCompany:"/editCompany",
  report1:"/report1",
  countryMaster:"/countryMaster",
  addCountry:"/addCountry",
  editCountry:"/editCountry",
  stateMaster:"/stateMaster",
  addState:"/addState",
  editState:"/editState",
  addDestination:"/addDestination",
  editDestination:"/editDestination",
  userMaster:"/userMaster",
  addUser:"/addUser",
  editUser:"/editUser",
  branchMaster:"/branchMaster",
  editBranch:"/editBranch",
  addBranch:"/addBranch",
  moduleMaster:"/moduleMaster",
  addModule:"/addModule",
  editModule:"/editModule",
  roleMaster:"/rolemaster", 
  addRole:"/addRole",
  warehouseMaster:"/warehouseMaster",
  addWarehouse:"/addWarehouse",
  editWarehouse:"/editWarehouse",
  numberingMaster:"/numberingMaster",
  addNumbering:"/addNumbering",
  editNumbering:"/editNumbering",
  currencyMaster:"/currencyMaster",
  addCurrency:"/addCurrency",
  itemMaster:"/itemMaster",
  addItem:"/addItem",
  editItem:"/editItem",
  itemCategoryMaster:"/itemCategoryMaster",
  addItemCategory:"/addItemCategory",
  editItemCategory:"/editItemCategory",
  
  coa:"/coa",
};


export const PREFIX={
  moduleID:"M",
  pageID:"PL",
  companyID:"C",
  branchId:"B",
  countryID:"CO",
  stateID:"ST",
  destinationID:"DEST",
  userID:"U",
  roleID:"R",
  wareHouseId:"W",
  noSeriesId:"NO"
};
